### ISSUE TITLE
Example for linux-arm64 and linux-amd64

### ISSUE THREAD

**Issue by asabya** [goreleaser/goreleaser-cross-example#4]
The repo lacks the `env` for 
```
goos:
      - linux
goarch:
      - arm64
      - amd64
```

**Comment by troian** [comment]
not sure i understood what you're trying to ask

**Comment by asabya** [comment]
What should be used as 
- CC
- CXX
- CGO_CFLAGS
- CGO_LDFLAGS
- PKG_CONFIG_SYSROOT_DIR
- PKG_CONFIG_PATH

for linux/amd64 and linux/arm64

**Comment by troian** [comment]
i still don't get the question.
would advise to check readme [here](https://github.com/goreleaser/goreleaser-cross)

**Comment by asabya** [comment]
Hi! Thanks for the quick replies. As I am looking at https://github.com/goreleaser/goreleaser-cross-example/blob/master/.goreleaser.yaml, it does not seem to cover the build config for linux/amd64 and linux/arm64.

I guess goreleaser-cross sheds light into it.

**Comment by troian** [comment]
i see now what you are looking for. will update this example at some point.
[here](https://github.com/ovrclk/akash/blob/master/.goreleaser.yaml) is immediate example covering your needs.

**Comment by asabya** [comment]
Perfect. That is exactly what I am looking for. Thanks

**Comment by asabya** [comment]
What should be the value for ["-linkmode={{ .Env.LINKMODE }}"](https://github.com/ovrclk/akash/blob/9bf75685865370befab0a21f3ff80552c8c9bd98/.goreleaser.yaml#L22)?
