### ISSUE TITLE
Why does the docker container need privileged access?

### ISSUE THREAD

**Issue by HenryNguyen5** [goreleaser/goreleaser-cross-example#5]
Is it for Docker in Docker support when Goreleaser is creating the docker images during build phase?

**Comment by troian** [comment]
did you try it without `--privileged` flag set?

**Comment by HenryNguyen5** [comment]
I wasn't able to try it on this repo in particular, since it doesnt pull the headers i need on an arm64 linux machine, but when I tried it on my own project it seemed to work. I thought that I might be missing something though that I would later run into which would need the `--priviledged` flag

I also see that you have set the flag in `Akash`, here https://github.com/ovrclk/akash/blob/master/make/releasing.mk#L89

**Comment by troian** [comment]
yeah, it refers to some old version of `goreleaser-cross` when it was having difficulties on github actions.
it looks to me that it is safe to remove it

**Comment by HenryNguyen5** [comment]
@troian I've opened a PR to update this :) https://github.com/goreleaser/goreleaser-cross-example/pull/6

**Comment by troian** [comment]
thanks @HenryNguyen5
